import { describe, it, expect, afterEach, vi } from "vitest";
import { setupKindeMock, mockClientConfig, getMockAuthURL } from "../mocks.js";
import { getInternalClient } from "../setup/index.js";
import type { ClientType } from "../setup/kindeSetupTypes.js";
import type { GrantType } from "@kinde-oss/kinde-typescript-sdk";
import request from "supertest";

describe("kindeAuthRouter", () => {
  const app = setupKindeMock();

  describe("handleRegister()", () => {
    const internalClient = getInternalClient();
    const registerMock = vi.spyOn(
      internalClient as ClientType<GrantType.AUTHORIZATION_CODE>,
      "register",
    );

    afterEach(() => {
      registerMock.mockClear();
    });

    it("redirects user to registration URL generated by internal client", async () => {
      const registerURL = getMockAuthURL({ start_page: "registration" });
      registerMock.mockResolvedValue(registerURL);
      const response = await request(app).get("/register");
      expect(response.status).toBe(302);
      expect(response.headers.location).toBe(registerURL.toString());
    });

    it("starts invitation registration flow with invitation_code and is_invitation", async () => {
      const registerURL = getMockAuthURL({ start_page: "registration" });
      registerMock.mockResolvedValue(registerURL);

      const response = await request(app)
        .get("/register")
        .query({ invitation_code: "inv_123" });

      expect(response.status).toBe(302);
      expect(registerMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.objectContaining({
          invitation_code: "inv_123",
          is_invitation: "true",
        }),
      );
    });

    it("does not forward blank invitation_code for registration flow", async () => {
      const registerURL = getMockAuthURL({ start_page: "registration" });
      registerMock.mockResolvedValue(registerURL);

      const response = await request(app)
        .get("/register")
        .query({ invitation_code: "   " });

      expect(response.status).toBe(302);
      expect(registerMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.not.objectContaining({ invitation_code: expect.anything() }),
      );
    });

    it("uses first invitation_code value when invitation_code is an array", async () => {
      const registerURL = getMockAuthURL({ start_page: "registration" });
      registerMock.mockResolvedValue(registerURL);

      const response = await request(app)
        .get("/register")
        .query("invitation_code=%20inv_first%20&invitation_code=inv_second");

      expect(response.status).toBe(302);
      expect(registerMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.objectContaining({
          invitation_code: "inv_first",
          is_invitation: "true",
        }),
      );
    });

    it("does not forward invitation_code when invitation_code is a non-string object", async () => {
      const registerURL = getMockAuthURL({ start_page: "registration" });
      registerMock.mockResolvedValue(registerURL);

      const response = await request(app)
        .get("/register")
        .query("invitation_code[raw]=abc");

      expect(response.status).toBe(302);
      expect(registerMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.not.objectContaining({ invitation_code: expect.anything() }),
      );
    });

    it("raises exception if optional organization code is invalid", async () => {
      const query = { org_code: "" };
      const response = await request(app).get("/register").query(query);
      expect(response.status).toBe(400);
      expect(response.text).toContain("org_code");
      expect(response.text).toContain("invalid value");
    });
  });
  describe("handleLogin()", () => {
    const internalClient = getInternalClient();
    const loginMock = vi.spyOn(
      internalClient as ClientType<GrantType.AUTHORIZATION_CODE>,
      "login",
    );

    afterEach(() => {
      loginMock.mockClear();
    });

    it("redirects user to login URL generated by internal client", async () => {
      const loginURL = getMockAuthURL();
      loginMock.mockResolvedValue(loginURL);
      const response = await request(app).get("/login");
      expect(response.status).toBe(302);
      expect(response.headers.location).toBe(loginURL.toString());
    });

    it("starts invitation login flow with invitation_code and is_invitation", async () => {
      const loginURL = getMockAuthURL();
      loginMock.mockResolvedValue(loginURL);

      const response = await request(app)
        .get("/login")
        .query({ invitation_code: "inv_123" });

      expect(response.status).toBe(302);
      expect(loginMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.objectContaining({
          invitation_code: "inv_123",
          is_invitation: "true",
        }),
      );
    });

    it("does not forward blank invitation_code for login flow", async () => {
      const loginURL = getMockAuthURL();
      loginMock.mockResolvedValue(loginURL);

      const response = await request(app)
        .get("/login")
        .query({ invitation_code: "   " });

      expect(response.status).toBe(302);
      expect(loginMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.not.objectContaining({ invitation_code: expect.anything() }),
      );
    });

    it("uses first invitation_code value when invitation_code is an array", async () => {
      const loginURL = getMockAuthURL();
      loginMock.mockResolvedValue(loginURL);

      const response = await request(app)
        .get("/login")
        .query("invitation_code=%20inv_first%20&invitation_code=inv_second");

      expect(response.status).toBe(302);
      expect(loginMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.objectContaining({
          invitation_code: "inv_first",
          is_invitation: "true",
        }),
      );
    });

    it("does not forward invitation_code when invitation_code is a non-string object", async () => {
      const loginURL = getMockAuthURL();
      loginMock.mockResolvedValue(loginURL);

      const response = await request(app)
        .get("/login")
        .query("invitation_code[raw]=abc");

      expect(response.status).toBe(302);
      expect(loginMock).toHaveBeenCalledWith(
        expect.anything(),
        expect.not.objectContaining({ invitation_code: expect.anything() }),
      );
    });

    it("raises exception if optional organization code is invalid", async () => {
      const query = { org_code: "" };
      const response = await request(app).get("/login").query(query);
      expect(response.status).toBe(400);
      expect(response.text).toContain("org_code");
      expect(response.text).toContain("invalid value");
    });
  });

  describe("handleCallback()", () => {
    const internalClient = getInternalClient();
    const redirectToAppMock = vi.spyOn(
      internalClient as ClientType<GrantType.AUTHORIZATION_CODE>,
      "handleRedirectToApp",
    );

    afterEach(() => {
      redirectToAppMock.mockClear();
    });

    it("redirects to siteUrl if internal client handles redirection successfully", async () => {
      redirectToAppMock.mockResolvedValue(undefined);
      const response = await request(app).get("/kinde_callback");
      expect(response.status).toBe(302);
      expect(redirectToAppMock).toHaveBeenCalledTimes(1);
      expect(response.headers.location).toBe(mockClientConfig.siteUrl);
    });

    it("redirects to unAuthorisedUrl if internal client fails to handle redirection", async () => {
      redirectToAppMock.mockRejectedValue(new Error("error"));
      const response = await request(app).get("/kinde_callback");
      expect(response.status).toBe(302);
      expect(response.headers.location).toBe(mockClientConfig.unAuthorisedUrl);
    });
  });
});
